---
- name: install nginx and prometheus-nginx-exporter
  ansible.builtin.apt:
    pkg:
    - nginx 
    - prometheus-nginx-exporter
    state: present

- name: copy default conf to nginx sites-enabled
  ansible.builtin.template:
    src: ./../templates/default.j2
    dest: /etc/nginx/sites-enabled/default
    mode: '0644'
  notify:
  - Restart nginx
  - Restart nginx-exporter

- name: start nginx and nginx node exporter
  ansible.builtin.service:
    name: "{{ item }}" 
    state: started 
    enabled: yes
  loop:
    - nginx
    - prometheus-nginx-exporter