- name: Get influxd exporter binary
  ansible.builtin.get_url:
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64
    dest: /usr/local/bin/prometheus-influxdb
    owner: prometheus
    mode: u+rwx

- name: copy pinger service file
  ansible.builtin.template:
    src: ./../templates/prometheus-influxdb-stats-exporter.service.j2
    dest: /etc/systemd/system/prometheus-influxdb.service

- name: start influxdb exporter service
  ansible.builtin.systemd:
    state: started
    enabled: true
    daemon_reload: true
    name: prometheus-influxdb