---

- name: Create grafana directory
  ansible.builtin.file:
    name: /opt/grafana/provisioning/{ item }
    state: directory
    recurse: true
  loop:
    - dashboards
    - datasources

- name: copy Grafana Datasource yaml
  ansible.builtin.copy:
    src: ./../files/datasource.yaml
    dest: /opt/grafana/provisioning/datasources/
  notify:
    - Restart Grafana Container

- name: configure Grafana
  ansible.builtin.template:
    src: ./../templates/grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  no_log: yes
  notify:
    - Restart Grafana Container

- name: copy Grafana Dashboard json
  ansible.builtin.copy:
    src: ./../files/{{ item }}
    dest: /opt/grafana/provisioning/dashboards/
  loop:
    - main.json
    - syslog.json
    - mysql.json
    - dashboards.yaml
  notify:
    - Restart Grafana Container

- name: copy Grafana Datasource yaml
  ansible.builtin.copy:
    src: ./../files/datasource.yaml
    dest: /opt/grafana/provisioning/datasources/
  notify:
    - Restart Grafana Container


- name: Grafana container
  ansible.builtin.docker_container:
    name: grafana
    image: grafana/grafana
    volumes: /opt/grafana:/etc/grafana
    published_ports: "{{ grafana_port }}:3000"
    restart_policy: always
  notify:
    - Restart Grafana Container
