---
- name: Install uWSGI and plugins
  ansible.builtin.apt:
    pkg:
    - uwsgi
    - uwsgi-plugin-python3
    state: present

- name: copy AGAMA conf files
  ansible.builtin.template:
    src: ./../templates/agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: '0600'
  no_log: true
  notify:
  - Restart uwsgi

- name: Start uwsgi
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: yes