{
 "title": "MySQL",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Slave sql running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_up{job=\"mysql\", instance=~\"Jns234-1:9104|Jns234-2:9104\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slave io running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running{instance=~\"Jns234-1:9104|Jns234-2:9104\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL server ids",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL server read only status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only{instance=~\"Jns234-2:9104|Jns234-1:9104\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL selects per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by() (rate(mysql_global_status_commands_total[1m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}