---
- name: Create agama dir
  ansible.builtin.file:
    name: /opt/agama
    owner: root
    group: root
    state: directory
    recurse: true

- name: Download Dockerfile and agama.py
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/{{ item }}
    dest: /opt/agama/{{ item }}
    owner: root
    group: root
  loop:
    - Dockerfile
    - agama.py

- name: Build agama image
  community.docker.docker_image:
    name: agama
    build:
      path: /opt/agama
      network: host
    source: build


- name: agama container
  ansible.builtin.docker_container:
    name: agama
    image: agama
    env:
      AGAMA_DATABASE_URI: mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}
    ports:
      - "{{ agama_docker_port }}:8000"
    restart_policy: always
  no_log: true

- name: agama container nuber 2
  ansible.builtin.docker_container:
    name: agama2
    image: agama
    env:
      AGAMA_DATABASE_URI: mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}
    ports:
      - "{{ agama_docker_port + 1 }}:8000"
    restart_policy: always
  no_log: true