---
- name: Create folder for keepalived
  ansible.builtin.file:
    path: /etc/keepalived/
    state: directory

- name: Configure keepalived
  ansible.builtin.template:
    src: ./../templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify:
    - restart keepalived

- name: Inatall keepalived
  ansible.builtin.apt: 
    name: keepalived
    state: present

- name: Start keepalived
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: yes

- name: creater keepalivescript user
  ansible.builtin.user:
    name: keepalivedScript
    shell: /bin/bash

#- name: Create keepalived dirs
#  ansible.builtin.file:
#    name: "{{ item }}"
#    state: directory
#    recurse: true
#  loop:
#    - /home/keepalivedScript/
#    - /home/etc/keepalived/

- name: Propagate keepalived script
  ansible.builtin.template:
    src: ./../templates/keepalivedScript.j2
    dest: /home/keepalivedScript/keepalivedScript
    owner: keepalivedScript
    mode: 0500

- name: Download keepalived exporter
  ansible.builtin.unarchive:
    src: https://github.com/mehdy/keepalived-exporter/releases/download/v1.3.2/keepalived-exporter-1.3.2.linux-386.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Create keepalived-exporter service
  ansible.builtin.template:
    src: ./../templates/keepalived-exporter.service.j2
    dest: /etc/systemd/system/keepalived-exporter.service
  notify: 
    - Systemctl daemon-reload
    - restart keepalived-exporter
    - restart haproxy

- name: Start service keepalived-exporter
  ansible.builtin.service:
    name: keepalived-exporter
    state: started
    enabled: yes