- name: Install prometheus 
  ansible.builtin.apt:
    pkg:
      - prometheus
    state: latest

- name: copy prometheus config
  ansible.builtin.template:
    src: ./../templates/prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify:
    - Restart prometheus

- name: copy prometheus default config
  ansible.builtin.template:
    src: ./../templates/prometheus.j2
    dest: /etc/default/prometheus
  notify:
    - Restart prometheus
  