---
- name: Get Bind9 and bind exporter
  ansible.builtin.apt:
    pkg:
    - bind9
    - prometheus-bind-exporter
    state: latest

- name: Copy conf.options to machine
  ansible.builtin.template:
    src: ./../templates/named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify:
  - Restart bind9

- name: Copy zone to machine
  ansible.builtin.template:
    src: ./../templates/zone.j2
    dest: /var/lib/bind/db.jankang.jk
  notify:
  - Restart rndc

- name: Copy zone config
  ansible.builtin.template:
    src: ./../templates/named.conf.local.j2
    dest: /etc/bind/named.conf.local     
  notify:
  - Restart bind9

- name: Bind exporter is started
  ansible.builtin.service:
    name: prometheus-bind-exporter
    state: started
    enabled: yes
