---
#- name: Ansible ping module
#  ansible.builtin.ping:

# - name: Create user juri 
#   ansible.builtin.user:
#     name: juri

# - name: Create user roman
#   ansible.builtin.user:
#     name: roman

# - name: Set authorized keys taken from url for juri
#   ansible.posix.authorized_key:
#     user: juri
#     state: present
#     key: https://github.com/hudolejev.keys

# - name: Set authorized keys taken from url for roman
#   ansible.posix.authorized_key:
#     user: juri
#     state: present
#     key: https://github.com/romankuchin.keys

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400
    update_cache: yes

- name: have prometheus node exporter on all machines
  ansible.builtin.apt:
    pkg:
    - prometheus-node-exporter
    state: latest

- name: Have ca-certificates package
  ansible.builtin.apt:
    pkg:
    - ca-certificates=20230311ubuntu0.20.04.1
    state: present

