---
#- name: Ansible ping module
#  ansible.builtin.ping:

# - name: Create user juri 
#   ansible.builtin.user:
#     name: juri

# - name: Create user roman
#   ansible.builtin.user:
#     name: roman

# - name: Set authorized keys taken from url for juri
#   ansible.posix.authorized_key:
#     user: juri
#     state: present
#     key: https://github.com/hudolejev.keys

# - name: Set authorized keys taken from url for roman
#   ansible.posix.authorized_key:
#     user: juri
#     state: present
#     key: https://github.com/romankuchin.keys

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400
    update_cache: yes

- name: have prometheus node exporter on all machines
  ansible.builtin.apt:
    pkg:
    - prometheus-node-exporter
    state: present

- name: Have ca-certificates package
  ansible.builtin.apt:
    pkg:
    - ca-certificates=20230311ubuntu0.20.04.1
    state: present

- name: configure syslog
  ansible.builtin.template:
    src: ./../templates/15-telegraf.conf.j2
    dest: /etc/rsyslog.d/15-telegraf.conf
  notify: Restart syslog

- name: start syslog
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: yes

- name: backup user
  ansible.builtin.user:
    name: backup
    home: /home/backup
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  no_log: true

- name: backup user known hosts
  ansible.builtin.template:
    src: ./../templates/known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup
  no_log: true


- name: create directory restore to backup user
  ansible.builtin.file:
    path: /home/backup/restore
    state: directory
    owner: backup
    group: backup
    mode: 0750

- name: install duplicity
  ansible.builtin.apt:
    name: duplicity
    state: present